language: go
branches:
  only: master

install:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
  - mkdir -p "$HOME/gopath2"
  - GOPATH="$HOME/gopath2" go get -u github.com/spf13/hugo
  - export GOPATH="$HOME/gopath2:$GOPATH" PATH="$HOME/gopath2/bin:$PATH"

cache:
  directories:
    - "$HOME/gopath2"

before_script:
  - mkdir public
  - cd public
  - git init
  - git config user.email "tim@mrgossett.com"
  - git config user.name "Tim Gossett"
  - git remote add origin https://github.com/MrGossett/mrgossett.github.io.git
  - git pull origin master
  - cd ..

script:
  - hugo -b https://mrgossett.com

before_deploy:
  - cd public
  - git add .
  - git commit -m "Publishing build $TRAVIS_BUILD_NUMBER" || true

deploy:
  provider: script
  script: git push origin master
  on:
    branch: master
