language: go
branches:
  only: master

install:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
  - mkdir -p "$HOME/bin"
  - export PATH="$HOME/bin:$PATH"
  - |
    which hugo || \
    curl -L https://github.com/spf13/hugo/releases/download/v0.15/hugo_0.15_linux_386.tar.gz -o "$HOME/hugo.tar.gz" && \
    tar -vxf "$HOME/hugo.tar.gz" && cd "$HOME/hugo" && ln -s hugo* hugo

cache:
  directories:
    - "$HOME/bin"

before_script:
  - mkdir public
  - cd public
  - git init
  - git config user.email "tim@mrgossett.com"
  - git config user.name "Tim Gossett"
  - git remote add origin https://github.com/MrGossett/mrgossett.github.io.git
  - git pull origin master
  - cd ..

script:
  - hugo -b http://mrgossett.com

before_deploy:
  - cd public
  - git add .
  - git commit -m "Publishing build $TRAVIS_BUILD_NUMBER" || true

deploy:
  provider: script
  script: git push origin master
  on:
    branch: master
